## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file main.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2p5 = RealNumber('2.5'); _sage_const_46 = Integer(46); _sage_const_48 = Integer(48); _sage_const_2p9 = RealNumber('2.9'); _sage_const_12 = Integer(12); _sage_const_51 = Integer(51)## This file (main.sagetex.sage) was *autogenerated* from main.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('main', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_12 
_st_.blockbegin()
try:
 Soya = DiGraph()             # creates an empty graph
 Soya.add_vertex("Soybean")
 Soya.add_vertex("Tofu")
 Soya.add_vertex("Soy sauce")
 Soya.add_vertex("Ponzu")
 Soya.add_vertex("Teriyaki")
 Soya.add_vertex("Dark soyasouce")
 Soya.add_edge("Soybean","Soy sauce")
 Soya.add_edge("Soybean","Fermented soybean paste")
 Soya.add_edge("Fermented soybean paste","Doubanjiang")
 Soya.add_edge("Fermented soybean paste","Hoisin sauce")
 Soya.add_edge("Soybean","Soy milk")
 Soya.add_edge("Soy milk","Tofu")
 Soya.add_edge("Soy sauce","Ponzu")
 Soya.add_edge("Soy sauce","Teriyaki")
 Soya.add_edge("Soy sauce","Dark soyasouce")
 Soya.set_latex_options(scale=_sage_const_2p9 )
 Soyap=Soya.plot()
 Soyap.save('Soya.eps')
 
 chili = DiGraph()             # creates an empty graph
 chili.add_vertex("Chili")
 chili.add_edge("Chili","Sambal")
 chili.add_edge("Chili","Dried chili")
 chili.add_edge("Chili","Smoked chili")
 chili.add_edge("Smoked chili","Chipotle sauce")
 chili.add_edge("Dried chili","Chili powder")
 chili.add_edge("Chili","Fermented chili")
 chili.add_edge("Fermented chili","Sriracha")
 chili.add_edge("Fermented chili","Hot Sauce")
 chili.set_latex_options(scale=_sage_const_2p5 ,edge_color='green')
 chilip=chili.plot()
 chilip.save('chili.eps')
except:
 _st_.goboom(_sage_const_46 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_48 
 _st_.inline(_sage_const_0 , latex(Soya))
except:
 _st_.goboom(_sage_const_48 )
try:
 _st_.current_tex_line = _sage_const_51 
 _st_.inline(_sage_const_1 , latex(chili))
except:
 _st_.goboom(_sage_const_51 )
_st_.endofdoc()

